namespace Apigen.Generator.Services;

/// <summary>
/// Writes generated files and remembers which paths were written, so files left over
/// from a previous run (schemas or operations removed from the spec) can be pruned.
/// </summary>
public class GeneratedFileTracker
{
  /// <summary>
  /// Marker from the auto-generated header. Prune deletes nothing without it: an output
  /// directory can legitimately contain hand-written code, such as transip's
  /// TransIpAuthTokenProvider, and losing that to a regeneration is unacceptable.
  /// </summary>
  private const string GeneratedMarker = "<auto-generated>";

  private static readonly string[] IgnoredDirectories = { "bin", "obj" };

  private readonly HashSet<string> _written = new(StringComparer.OrdinalIgnoreCase);

  /// <summary>
  /// Files written during this run, as full paths.
  /// </summary>
  public IReadOnlyCollection<string> WrittenFiles => _written;

  public async Task WriteAsync(string path, string content)
  {
    string fullPath = Path.GetFullPath(path);
    string? directory = Path.GetDirectoryName(fullPath);
    if (!string.IsNullOrEmpty(directory))
    {
      Directory.CreateDirectory(directory);
    }

    _written.Add(fullPath);
    await File.WriteAllTextAsync(fullPath, content);
  }

  /// <summary>
  /// Delete C# files under <paramref name="directories"/> that this run did not write and that
  /// carry the auto-generated header. Files without that header are kept and reported: they
  /// were put there by a human, or by a generator version that predates the header.
  /// Build output (bin/obj) is left alone.
  /// </summary>
  public PruneResult Prune(IEnumerable<string> directories)
  {
    PruneResult result = new();

    foreach (string directory in directories.Distinct(StringComparer.OrdinalIgnoreCase))
    {
      if (!Directory.Exists(directory))
      {
        continue;
      }

      foreach (string file in Directory.EnumerateFiles(directory, "*.cs", SearchOption.AllDirectories))
      {
        string fullPath = Path.GetFullPath(file);

        if (_written.Contains(fullPath) || IsBuildOutput(directory, fullPath))
        {
          continue;
        }

        if (!IsGenerated(fullPath))
        {
          result.Kept.Add(fullPath);
          continue;
        }

        File.Delete(fullPath);
        result.Deleted.Add(fullPath);
      }
    }

    return result;
  }

  private static bool IsGenerated(string path)
  {
    using StreamReader reader = new(path);

    for (int line = 0; line < 20; line++)
    {
      string? content = reader.ReadLine();
      if (content == null)
      {
        return false;
      }

      if (content.Contains(GeneratedMarker, StringComparison.Ordinal))
      {
        return true;
      }
    }

    return false;
  }

  private static bool IsBuildOutput(string root, string fullPath)
  {
    string relative = Path.GetRelativePath(root, fullPath);
    string[] segments = relative.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

    return segments.Length > 1 &&
           segments[..^1].Any(segment => IgnoredDirectories.Contains(segment, StringComparer.OrdinalIgnoreCase));
  }
}

/// <summary>
/// Outcome of a prune pass.
/// </summary>
public class PruneResult
{
  public List<string> Deleted { get; } = new();

  /// <summary>
  /// Files this run did not write but that carry no auto-generated header, so they were left
  /// alone.
  /// </summary>
  public List<string> Kept { get; } = new();
}
