using Apigen.Generator.Models;

namespace Apigen.Generator.Tests.Models;

public class HeaderOptionsTests
{
  [Fact]
  public void GenerateHeader_IncludeHeaderFalse_ReturnsEmptyString()
  {
    HeaderOptions options = new() { IncludeHeader = false };

    string result = options.GenerateHeader("test.yaml");

    Assert.Equal(string.Empty, result);
  }

  [Fact]
  public void GenerateHeader_IncludeTimestampFalse_OmitsTimestampLine()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeTimestamp = false,
      IncludeSource = false,
      IncludeGeneratorInfo = false,
      IncludeConfigInfo = false
    };

    string result = options.GenerateHeader("test.yaml");

    Assert.DoesNotContain("Generated on:", result);
  }

  [Fact]
  public void GenerateHeader_IncludeTimestampTrue_IncludesTimestampLine()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeTimestamp = true
    };

    string result = options.GenerateHeader("test.yaml");

    Assert.Contains("Generated on:", result);
    Assert.Contains("UTC", result);
  }

  [Fact]
  public void GenerateHeader_IncludeSourceTrue_IncludesSourceFilePath()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeSource = true,
      IncludeGeneratorInfo = false,
      IncludeTimestamp = false,
      IncludeConfigInfo = false
    };

    string result = options.GenerateHeader("openapi.yaml");

    Assert.Contains("Source: openapi.yaml", result);
  }

  [Fact]
  public void GenerateHeader_IncludeSourceTrue_WithApiTitle_IncludesApiLine()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeSource = true
    };

    string result = options.GenerateHeader("spec.yaml", apiTitle: "My API");

    Assert.Contains("API: My API", result);
  }

  [Fact]
  public void GenerateHeader_IncludeSourceTrue_WithApiVersion_IncludesVersionLine()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeSource = true
    };

    string result = options.GenerateHeader("spec.yaml", apiVersion: "2.0");

    Assert.Contains("Version: 2.0", result);
  }

  [Fact]
  public void GenerateHeader_IncludeGeneratorInfoTrue_IncludesGeneratorLine()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeGeneratorInfo = true,
      IncludeSource = false,
      IncludeTimestamp = false,
      IncludeConfigInfo = false
    };

    string result = options.GenerateHeader("test.yaml");

    Assert.Contains("Generated by: ApiGenerator", result);
  }

  [Fact]
  public void GenerateHeader_IncludeGeneratorInfoFalse_OmitsGeneratorLine()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeGeneratorInfo = false,
      IncludeSource = false,
      IncludeTimestamp = false,
      IncludeConfigInfo = false
    };

    string result = options.GenerateHeader("test.yaml");

    Assert.DoesNotContain("Generated by:", result);
  }

  [Fact]
  public void GenerateHeader_CustomText_IncludedInOutput()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      CustomText = "Do not edit this file manually.",
      IncludeGeneratorInfo = false,
      IncludeSource = false,
      IncludeTimestamp = false,
      IncludeConfigInfo = false
    };

    string result = options.GenerateHeader("test.yaml");

    Assert.Contains("Do not edit this file manually.", result);
  }

  [Fact]
  public void GenerateHeader_AllFlagsDisabled_ProducesMinimalHeader()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeTimestamp = false,
      IncludeSource = false,
      IncludeGeneratorInfo = false,
      IncludeConfigInfo = false,
      CustomText = null
    };

    string result = options.GenerateHeader("test.yaml");

    Assert.Contains("<auto-generated>", result);
    Assert.Contains("</auto-generated>", result);
    Assert.DoesNotContain("Generated by:", result);
    Assert.DoesNotContain("Generated on:", result);
    Assert.DoesNotContain("Source:", result);
  }

  [Fact]
  public void GenerateHeader_Default_IncludesAutoGeneratedTags()
  {
    HeaderOptions options = new();

    string result = options.GenerateHeader("test.yaml");

    Assert.Contains("<auto-generated>", result);
    Assert.Contains("</auto-generated>", result);
    Assert.Contains("Changes to this file may cause incorrect behavior", result);
  }

  [Fact]
  public void GenerateHeader_IncludeConfigInfo_WithCustomizations_IncludesConfigLine()
  {
    HeaderOptions options = new()
    {
      IncludeHeader = true,
      IncludeConfigInfo = true,
      IncludeGeneratorInfo = false,
      IncludeSource = false,
      IncludeTimestamp = false
    };

    GeneratorConfiguration config = new()
    {
      PropertyOverrides = [new PropertyOverride { PropertyFilter = "test" }]
    };

    string result = options.GenerateHeader("test.yaml", config: config);

    Assert.Contains("Config:", result);
    Assert.Contains("1 customizations", result);
  }
}
