namespace Apigen.Generator.Models;

public class HeaderOptions
{
  /// <summary>
  /// Whether to include an auto-generated header in each file
  /// </summary>
  public bool IncludeHeader { get; set; } = true;

  /// <summary>
  /// Whether to include the generation timestamp in the header
  /// </summary>
  public bool IncludeTimestamp { get; set; } = true;

  /// <summary>
  /// Whether to include the source OpenAPI spec path in the header
  /// </summary>
  public bool IncludeSource { get; set; } = true;

  /// <summary>
  /// Whether to include the generator version in the header
  /// </summary>
  public bool IncludeGeneratorInfo { get; set; } = true;

  /// <summary>
  /// Whether to include configuration information in the header
  /// </summary>
  public bool IncludeConfigInfo { get; set; } = true;

  /// <summary>
  /// Custom header text to include
  /// </summary>
  public string? CustomText { get; set; }

  /// <summary>
  /// Generate the header comment for a file
  /// </summary>
  public string GenerateHeader(
    string sourceFile,
    string? apiTitle = null,
    string? apiVersion = null,
    GeneratorConfiguration? config = null)
  {
    if (!IncludeHeader)
    {
      return string.Empty;
    }

    string indent = config?.Formatting?.GetIndentation() ?? "    ";
    List<string> lines = new();

    lines.Add("//");
    lines.Add("// <auto-generated>");

    if (!string.IsNullOrEmpty(CustomText))
    {
      lines.Add($"// {CustomText}");
      lines.Add("//");
    }

    if (IncludeGeneratorInfo)
    {
      lines.Add("// Generated by: ApiGenerator");
    }

    if (IncludeTimestamp)
    {
      lines.Add($"// Generated on: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
    }

    if (IncludeSource)
    {
      lines.Add($"// Source: {sourceFile}");
      if (!string.IsNullOrEmpty(apiTitle))
      {
        lines.Add($"// API: {apiTitle}");
      }

      if (!string.IsNullOrEmpty(apiVersion))
      {
        lines.Add($"// Version: {apiVersion}");
      }
    }

    if (IncludeConfigInfo && config != null)
    {
      bool hasCustomizations = config.PropertyOverrides.Count > 0 || config.TypeNameOverrides.Count > 0 ||
                               config.JsonConverters.Count > 0;
      if (hasCustomizations)
      {
        lines.Add("//");
        lines.Add(
          $"// Config: {config.Formatting.IndentWidth}{(config.Formatting.UseSpaces ? "sp" : "tab")}, {config.PropertyOverrides.Count + config.TypeNameOverrides.Count + config.JsonConverters.Count} customizations");
      }
    }

    lines.Add("//");
    lines.Add("// Changes to this file may cause incorrect behavior and will be lost if");
    lines.Add("// the code is regenerated.");
    lines.Add("// </auto-generated>");
    lines.Add("//");

    return string.Join(Environment.NewLine, lines) + Environment.NewLine;
  }
}