using Apigen.Generator.Services;

namespace Apigen.Generator.Tests.Services;

public class GeneratedFileTrackerTests : IDisposable
{
  private readonly string _root = Path.Combine(Path.GetTempPath(), $"apigen-prune-{Guid.NewGuid():N}");

  private const string GeneratedContent = "//\n// <auto-generated>\n// </auto-generated>\n//\npublic class C { }";

  public GeneratedFileTrackerTests() => Directory.CreateDirectory(_root);

  public void Dispose()
  {
    if (Directory.Exists(_root))
    {
      Directory.Delete(_root, true);
    }
  }

  private string CreateFile(string relativePath, string content = GeneratedContent)
  {
    string path = Path.Combine(_root, relativePath);
    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    File.WriteAllText(path, content);
    return path;
  }

  [Fact]
  public async Task WriteAsync_RecordsFileAsWritten()
  {
    GeneratedFileTracker tracker = new();
    string path = Path.Combine(_root, "Model.cs");

    await tracker.WriteAsync(path, GeneratedContent);

    Assert.True(File.Exists(path));
    Assert.Contains(Path.GetFullPath(path), tracker.WrittenFiles);
  }

  [Fact]
  public async Task WriteAsync_CreatesMissingDirectories()
  {
    GeneratedFileTracker tracker = new();
    string path = Path.Combine(_root, "Requests", "Nested", "Model.cs");

    await tracker.WriteAsync(path, GeneratedContent);

    Assert.True(File.Exists(path));
  }

  [Fact]
  public async Task Prune_DeletesGeneratedFilesNotWrittenThisRun()
  {
    GeneratedFileTracker tracker = new();
    await tracker.WriteAsync(Path.Combine(_root, "Kept.cs"), GeneratedContent);
    string stale = CreateFile("Stale.cs");

    PruneResult result = tracker.Prune(new[] { _root });

    Assert.False(File.Exists(stale));
    Assert.Equal(new[] { Path.GetFullPath(stale) }, result.Deleted);
    Assert.True(File.Exists(Path.Combine(_root, "Kept.cs")));
  }

  [Fact]
  public void Prune_KeepsHandWrittenFiles()
  {
    GeneratedFileTracker tracker = new();
    string handWritten = CreateFile(
      "TransIpAuthTokenProvider.cs",
      "// This file is hand-written and is NOT regenerated by the apigen-dotnet generator.\npublic class P { }");

    PruneResult result = tracker.Prune(new[] { _root });

    Assert.True(File.Exists(handWritten));
    Assert.Empty(result.Deleted);
    Assert.Equal(new[] { Path.GetFullPath(handWritten) }, result.Kept);
  }

  [Fact]
  public void Prune_KeepsFilesWhereTheMarkerIsBuriedTooDeep()
  {
    GeneratedFileTracker tracker = new();
    string file = CreateFile("Late.cs", string.Concat(Enumerable.Repeat("// filler\n", 40)) + "// <auto-generated>");

    PruneResult result = tracker.Prune(new[] { _root });

    Assert.True(File.Exists(file));
    Assert.Empty(result.Deleted);
  }

  [Fact]
  public async Task Prune_DeletesStaleFilesInSubdirectories()
  {
    GeneratedFileTracker tracker = new();
    await tracker.WriteAsync(Path.Combine(_root, "Requests", "Current.cs"), GeneratedContent);
    string stale = CreateFile(Path.Combine("Requests", "Removed.cs"));

    PruneResult result = tracker.Prune(new[] { _root });

    Assert.False(File.Exists(stale));
    Assert.Single(result.Deleted);
  }

  [Fact]
  public void Prune_IgnoresBuildOutput()
  {
    GeneratedFileTracker tracker = new();
    string objFile = CreateFile(Path.Combine("obj", "Debug", "AssemblyInfo.cs"));
    string binFile = CreateFile(Path.Combine("bin", "Release", "Ref.cs"));

    PruneResult result = tracker.Prune(new[] { _root });

    Assert.True(File.Exists(objFile));
    Assert.True(File.Exists(binFile));
    Assert.Empty(result.Deleted);
    Assert.Empty(result.Kept);
  }

  [Fact]
  public void Prune_LeavesNonCSharpFilesAlone()
  {
    GeneratedFileTracker tracker = new();
    string csproj = Path.Combine(_root, "Project.csproj");
    File.WriteAllText(csproj, "<Project />");

    PruneResult result = tracker.Prune(new[] { _root });

    Assert.True(File.Exists(csproj));
    Assert.Empty(result.Deleted);
  }

  [Fact]
  public void Prune_MissingDirectory_IsIgnored()
  {
    GeneratedFileTracker tracker = new();

    PruneResult result = tracker.Prune(new[] { Path.Combine(_root, "does-not-exist") });

    Assert.Empty(result.Deleted);
    Assert.Empty(result.Kept);
  }
}
